### ISSUE TITLE
Add train 

### ISSUE THREAD

**Issue by faroit** [sigsep/sigsep-mus-previews#10]
I think for some applications we might also want the training previews for 30s and 7s duration. 

@deeuu do you have computed them as well and can maybe update the release? 🙏

**Comment by deeuu** [comment]
Hey,

I only computed them for the test set. Can easily be done though..perhaps as a separate release?

Are they needed for the website?

**Comment by faroit** [comment]
> Are they needed for the website?

exactly. Also we are going to release a magnitude-spectrogram dataset using the 30s previews for educational purposes.

**Comment by deeuu** [comment]
Okay perhaps I can attempt this over the weekend.

**Comment by faroit** [comment]
I just did it, seems to look okay

**Comment by faroit** [comment]
I've updated the release
