### ISSUE TITLE
7s previews differ significantly from 30s previews

### ISSUE THREAD

**Issue by faroit** [sigsep/sigsep-mus-previews#11]
I did some rehearsal of the selections and found some significant flaws with the 7s preview segments.

e.g.:

in `PR - Happy Daze` the output selects: `start: 95; stop:125s`for the 30s segments and `[22s; 29s]` for the 7s previews. The problems is that the 7s preview part does not contain any vocals. So I assume there is some bug somewhere. As far as I checked, the 30s previews are okay.

@deeuu any idea?

**Comment by deeuu** [comment]
Hey,

I also discovered this and checked it out.
It's because the _backing vocals_ are sustained over a long portion of time, so they dominate the activity selection. So not a bug, just a side effect of the grouping (they are part of the vocals stem).

I think we are simply discounting this song from our selection procedure used to obtained the stimuli for the listening test.

**Comment by deeuu** [comment]
Also note that the `[22s; 29s]` you mentioned are relative to the start of the 30s portion, i.e. a cut-list sample start index of 0 would be the first sample in the 30s preview.

The 7s previews should be generated using the 30s previews as input (see the [latest release notes](https://github.com/sigsep/sigsep-mus-cutlist-generator/releases/tag/v0.3))

@faroit Can you verify that the problematic 7s preview of `PR - Happy Daze` is also part of the 30s preview (it should be)?

**Comment by faroit** [comment]
🤦‍♂️

**Comment by faroit** [comment]
I spent too much time on my thesis, sorry... I forgot what we agreed on

**Comment by deeuu** [comment]
Probably not as long as i spent on mine ;-) 

At least we are both aware of this now. Let me know if anything else pops up

**Comment by deeuu** [comment]
No problem at all (I spent way too long on mine!). 

Please let us know if you make any changes or a new release.
