### ISSUE TITLE
7s cut-list times

### ISSUE THREAD

**Issue by deeuu** [sigsep/sigsep-mus-previews#12]
@faroit The times in [the 7s preview cut-list](https://github.com/sigsep/sigsep-mus-cutlist-generator/releases/download/v0.3/7s_previews.csv) are relative to the start of the 30s previews. Should we make this clear in the README?

I overlooked this when extracting the BSS Eval scores for the 7s previews from the [main results file](https://github.com/sigsep/sigsep-mus-2018-analysis/releases).

**Comment by faroit** [comment]
absolutely. I fell for it myself multiple times ;-)
