### ISSUE TITLE
Ramps

### ISSUE THREAD

**Issue by deeuu** [sigsep/sigsep-mus-previews#6]
@faroit Should we allow for amplitude envelope ramps to be applied to the onset and offset of the cropped audio?

I'm happy to leave this as a post-processing step for the listening test.

**Comment by faroit** [comment]
While I think ramps should def be there for any kind of playback, I feel that the "raw" 30s subset should come without so that it will not loose the reproducibility to the bsseval scores of the matching excerpts.

For playback I [used web audio based fading](https://github.com/faroit/sisec-mus-website/blob/master/src/Dataset.vue#L103). 

Furthermore for MUSHRA tests the ITU recommends to use 5 ms fade in and 5 ms fade out with a raised cosine envelope for switching the tracks. 

I think we can do this for (5ms is quite short) for the listening test subset.

**Comment by deeuu** [comment]
Yeah, I also do on-the-fly fading when triggering clips, but the issue is when the playback is looped.
I also agree that 5ms is too short, something like 20ms is more suitable.

Perhaps this should be left as a post-processing stage (not this project), where additional steps like loudness normalisation can be applied.

Close if you agree.

**Comment by faroit** [comment]
okay, lets do this in a separate project and leave this to just finding the start/end positions. 
Last year I used [this code](https://github.com/faroit/sisec-mus-trim) to generate the actual audio data for the websites. Lets fork it and update it to add the experiments post-processing there.

**Comment by faroit** [comment]
@deeuu actually it makes sense to disable the audio rendering in this project by default and just let users enable it to listen to the cut excerpts. Do you agree?

**Comment by deeuu** [comment]
So this project should only generate the csv files for the 30s and 10s (maybe smaller) previews?

Then we implement a revised version of the [preview-generator](https://github.com/faroit/sisec-mus-trim)? Perhaps that project could be less specific, and segment all audio locataed within the given subdirectories.

Just to be clear: do we need the 10s segment to taken from the 30s segment because that will be the only portion of the submitted audio (from SiSEC-MUS participants) that we have access to? So it needs to be incorporated here.

**Comment by deeuu** [comment]
Actually, after playing around a bit, I think we can leave it as a simple csv generator for the desired preview duration.

To generate the audio for the listening test, we just re-run `generate_previews.py` on the 30s preview audio, generating a second csv file, e.g. where a start sample index 0 would be the first sample of the first 30s preview.

Then we can run the trimmer as needed.

Let me update and send a pull-request for you to review.

**Comment by faroit** [comment]
> So this project should only generate the csv files for the 30s and 10s (maybe smaller) previews?

yes

> Just to be clear: do we need the 10s segment to taken from the 30s segment because that will be the only portion of the submitted audio (from SiSEC-MUS participants) that we have access to? So it needs to be incorporated here.

well, that is not the main reason, as we hope that this time we will be able to host the full participants data. I

ts more that it makes sense to have _some_ criterion to select the 10s segments and I thought its good to stick with the idea of using the source activity here. Also the website will use the 30s previews that would allow to maybe switch to a listening test mode and have the 10s from the same excerpts presented on the website...

**Comment by faroit** [comment]
> To generate the audio for the listening test, we just re-run generate_previews.py on the 30s preview audio, generating a second csv file, e.g. where a start sample index 0 would be the first sample of the first 30s preview.

you mean, we generate the 30s previews and then use the same code to select 10s on the 30s dataset using the same activity based feature?

**Comment by deeuu** [comment]
> you mean, we generate the 30s previews and then use the same code to select 10s on the 30s dataset using the same activity based feature?

Yes.

I thought you were only hosting the 30s data, and hence the 10s segments should be taken from the 30s previews. If that is is not the case, then the 10s could come from anywhere in each song, which means we can decouple it from the 30s previews.

> and have the 10s from the same excerpts presented on the website

In that case, the 10s should depend on the 30s previews. 

I'll send a pull-request anyway so either approach can work.
