### ISSUE TITLE
Name of this repo

### ISSUE THREAD

**Issue by deeuu** [sigsep/sigsep-mus-previews#8]
Should we call this one:

`sigsep-mus-2018-cutlist-generator`

[sigsep-mus-2018-trim](https://github.com/deeuu/sigsep-mus-2018-trim) should then probably be renamed to `sigsep-mus-2018-preview-generator` (which you might want to fork to the [sigsep](https://github.com/sigsep) organisation).

If you're not fussed then let's leave it!

**Comment by faroit** [comment]
I like both!

**Comment by faroit** [comment]
Its renamed....

I would prefer to have the sigsep org as the base and our personal github accounts maintaining the forks. So maybe we can move yours here and I will cut the fork dependency to `sisec-mus-previews`

**Comment by deeuu** [comment]
Thanks!

Yeah, I agree. I'm not a member of this organisation so I just made a start using my personal account.
